language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - $HOME/.npm
  - $HOME/.cache
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: JhLv7be0KMUxEmcSv/VaWNEQkPa1PBWFdKxzbOo1XX01UA421FXn5dUb7t20ZHeJDq3UWJjBjM77fMpJFE7lNepeWaJVMB1th5bGI23HgO3S+wB3CvYcvF8bLMxm5xeAJcD8T7igOMo8DhfVHSQCapXkZD5GOz1phV8iA3R+yFnxca2rEe6rlTExvPkjV9c9cDYjFDIToai+AFBMojdcj9jdrIZ6FHd3/xKNQFJEEDoqnYW+fnwqs/a1a4KyBBdIE65JbNXg4f8veTa7VAsiFdjUwtbLFyGBIDMI9qBNhGzTR2aAvXloPkZkBxEFDQJF0zE2LvBnOxT8oi6OqjPPQrqHYvoHbbTWax65iCr/VjP3Khd/uBiAfgqVWvZTthpI1OVHpNHnKjNc5CvdN1UdyodHMa74wNzGBOm/dIE74ltWaCNrSccFQZ7eqm9NltOSF1aS17NHkp6Vxzdri9YgsNcQXshyw88f+4Qa673v8f5wwIODzNFaRqIIzjvnBBHWa0jDzwbvpBNvbWInEpW4ewfnbS/QaIZy1zt6al/KBxepj/VwX4XLN0S3151fpWNtj/4BM24ViKqPnZstikMo9qyc0rpm4Mwzn5mjfSaWzfHtNJNMH9Dby+CDNCT90G9+OMgCOnCYebKRrzVsx5uGd0YQyJe73/PeP+x6v/PxCmY=
  app: still-oasis-70603
  on:
    repo: lmcardle/peepchat_ui
